#!/usr/bin/env bash
# install web server
function install_and_configure_nginx(){
	sudo apt-get -y update
	sudo apt-get -y install nginx
	#sudo ufw allow "Nginx HTTP"
	#sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
	echo "Hello World!" > /var/www/html/index.html
	service nginx start
}
install_and_configure_nginx;
