#!/usr/bin/env bash
# configure

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo sevice nginx restart
