#!/usr/bin/env bash
#proccess
file="/var/run/myscript.pid"
if [ ! -e "$file" ]; then
	touch "$file"
fi
sleep 2 &
echo "$!" > "$file"

trap 'echp "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

trap "echo Y U no love me?!" SIGINT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
