#!/usr/bin/env bash
#manage my proccess
command="$1"
if [ -z "$command" ]; then
	echo "Usage: manage_my_proccess {start|stop|restart}"
	exit
fi

if [ "$command" == "start" ]; then
	bash ./manage_my_proccess &
	echo "$!" > /var/run/my_proccess.pid
	echo "manage_my_proccess started"

elif [ "$command" == "stop" ]; then
	[ -e "/var/run/my_proccess.pid" ] && pkill -f './manage_my_proccess' && rm /var/run/my_proccess.pid
	echo "mange_my_proccess stopped"

elif [ "$command" == "restart" ]; then
	"$0" stop >& /dev/null
	"$0" start >& /dev/null
	echo "manage_my_proccess restarted"

else
	echo "Usage: manage_my_proccess {start|stop|restart}"
fi
